/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as IncubatorsRouteImport } from './routes/incubators'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EcosystemMentorsRouteImport } from './routes/ecosystem/mentors'
import { Route as AboutTeamRouteImport } from './routes/about/team'
import { Route as AboutBoardRouteImport } from './routes/about/board'
import { Route as SectionSlugRouteImport } from './routes/$section/$slug'

const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const IncubatorsRoute = IncubatorsRouteImport.update({
  id: '/incubators',
  path: '/incubators',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemMentorsRoute = EcosystemMentorsRouteImport.update({
  id: '/ecosystem/mentors',
  path: '/ecosystem/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTeamRoute = AboutTeamRouteImport.update({
  id: '/about/team',
  path: '/about/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutBoardRoute = AboutBoardRouteImport.update({
  id: '/about/board',
  path: '/about/board',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSlugRoute = SectionSlugRouteImport.update({
  id: '/$section/$slug',
  path: '/$section/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incubators': typeof IncubatorsRoute
  '/mentors': typeof MentorsRoute
  '/$section/$slug': typeof SectionSlugRoute
  '/about/board': typeof AboutBoardRoute
  '/about/team': typeof AboutTeamRoute
  '/ecosystem/mentors': typeof EcosystemMentorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incubators': typeof IncubatorsRoute
  '/mentors': typeof MentorsRoute
  '/$section/$slug': typeof SectionSlugRoute
  '/about/board': typeof AboutBoardRoute
  '/about/team': typeof AboutTeamRoute
  '/ecosystem/mentors': typeof EcosystemMentorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/incubators': typeof IncubatorsRoute
  '/mentors': typeof MentorsRoute
  '/$section/$slug': typeof SectionSlugRoute
  '/about/board': typeof AboutBoardRoute
  '/about/team': typeof AboutTeamRoute
  '/ecosystem/mentors': typeof EcosystemMentorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/incubators'
    | '/mentors'
    | '/$section/$slug'
    | '/about/board'
    | '/about/team'
    | '/ecosystem/mentors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/incubators'
    | '/mentors'
    | '/$section/$slug'
    | '/about/board'
    | '/about/team'
    | '/ecosystem/mentors'
  id:
    | '__root__'
    | '/'
    | '/incubators'
    | '/mentors'
    | '/$section/$slug'
    | '/about/board'
    | '/about/team'
    | '/ecosystem/mentors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncubatorsRoute: typeof IncubatorsRoute
  MentorsRoute: typeof MentorsRoute
  SectionSlugRoute: typeof SectionSlugRoute
  AboutBoardRoute: typeof AboutBoardRoute
  AboutTeamRoute: typeof AboutTeamRoute
  EcosystemMentorsRoute: typeof EcosystemMentorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incubators': {
      id: '/incubators'
      path: '/incubators'
      fullPath: '/incubators'
      preLoaderRoute: typeof IncubatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/mentors': {
      id: '/ecosystem/mentors'
      path: '/ecosystem/mentors'
      fullPath: '/ecosystem/mentors'
      preLoaderRoute: typeof EcosystemMentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/team': {
      id: '/about/team'
      path: '/about/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof AboutTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/board': {
      id: '/about/board'
      path: '/about/board'
      fullPath: '/about/board'
      preLoaderRoute: typeof AboutBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/$slug': {
      id: '/$section/$slug'
      path: '/$section/$slug'
      fullPath: '/$section/$slug'
      preLoaderRoute: typeof SectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncubatorsRoute: IncubatorsRoute,
  MentorsRoute: MentorsRoute,
  SectionSlugRoute: SectionSlugRoute,
  AboutBoardRoute: AboutBoardRoute,
  AboutTeamRoute: AboutTeamRoute,
  EcosystemMentorsRoute: EcosystemMentorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
